Repository panther-labs/panther-analysis, pull requests merged in 2023-07, with the labels that each got.

#844 Fixes misnaming of github_repo_collaborator_change
  indexes/github.md
  rules/github_rules/github_repo_collaborator_change.yml
Labels: documentation

#841 Rework a few GCP detections to use deep_walk
  global_helpers/panther_base_helpers.py
  rules/gcp_audit_rules/gcp_access_attempts_violating_vpc_service_controls.py
  rules/gcp_audit_rules/gcp_access_attempts_violating_vpc_service_controls.yml
  rules/gcp_audit_rules/gcp_log_bucket_or_sink_deleted.py
  rules/gcp_audit_rules/gcp_permissions_granted_to_create_or_manage_service_account_key.py
  rules/gcp_k8s_rules/gcp_k8s_exec_into_pod.py
Labels: python, tuning

#847 fix: Update list of "safe" TLS ciphers in AWS ALB SSL/TLS policy
  policies/aws_load_balancer_policies/aws_alb_ssl_policy.py
  policies/aws_load_balancer_policies/aws_alb_ssl_policy.yml
Labels: tuning

#849 fix: explicitly ignore top level enrichments that start with 'p_any_' in the key name
  global_helpers/panther_lookuptable_helpers.py
Labels: bug

#850 fix: CS base64 rule fails for some event types
  data_models/crowdstrike_fdr_data_model.py
  rules/crowdstrike_rules/crowdstrike_base64_encoded_args.py
Labels: bug

#852 New: Tailscale Detections and Pack
  global_helpers/global_filter_tailscale.py
  global_helpers/global_helpers_test.py
  global_helpers/panther_tailscale_helpers.py
  packs/tailscale.yml
  rules/tailscale_rules/tailscale_https_disabled.py
  rules/tailscale_rules/tailscale_https_disabled.yml
  rules/tailscale_rules/tailscale_machine_approval_requirements_disabled.py
  rules/tailscale_rules/tailscale_machine_approval_requirements_disabled.yml
  rules/tailscale_rules/tailscale_magicdns_disabled.py
  rules/tailscale_rules/tailscale_magicdns_disabled.yml
Labels: rules

#857 feat: some detections for Azure.SignIn log type
  global_helpers/global_helpers_test.py
  global_helpers/panther_azuresignin_helpers.py
  packs/azure_signin.yml
  rules/azure_signin_rules/azure_failed_signins.py
  rules/azure_signin_rules/azure_failed_signins.yml
  rules/azure_signin_rules/azure_legacyauth.py
  rules/azure_signin_rules/azure_legacyauth.yml
Labels: rules
