Repository panther-labs/panther-analysis, pull requests merged in 2023-02, with the labels that each got.

#667 tune: standard_rule/brute_force_by_ip
  rules/standard_rules/brute_force_by_ip.yml
Labels: tuning

#625 unmanaged detections tuning
  queries/crowdstrike_queries/AWS_Authentication_from_CrowdStrike_Unmanaged_Device.yml
  queries/crowdstrike_queries/Okta_Login_From_CrowdStrike_Unmanaged_Device.yml
  queries/crowdstrike_queries/onepass_login_from_crowdstrike_unmanaged_device.yml
  rules/crowdstrike_rules/aws_authentication_from_crowdstrike_unmanaged_device.py
  rules/crowdstrike_rules/aws_authentication_from_crowdstrike_unmanaged_device.yml
  rules/crowdstrike_rules/okta_login_from_crowdstrike_unmanaged_device.py
  rules/crowdstrike_rules/okta_login_from_crowdstrike_unmanaged_device.yml
  rules/crowdstrike_rules/onepassword_login_from_crowdstrike_unmanaged_device.py
  rules/crowdstrike_rules/onepassword_login_from_crowdstrike_unmanaged_device.yml
Labels: tuning

#678 chore: tune out aws config checking on ec2 traffic mirroring
  rules/aws_cloudtrail_rules/aws_ec2_traffic_mirroring.py
  rules/aws_cloudtrail_rules/aws_ec2_traffic_mirroring.yml
Labels: tuning

#687 Add Dropbox Team Member Linked App Rule
  rules/dropbox_rules/dropbox_linked_team_application_added.py
  rules/dropbox_rules/dropbox_linked_team_application_added.yml
Labels: rules

#695 New detection: alert when a new asana service account is created
  packs/asana.yml
  rules/asana_rules/asana_service_account_created.py
  rules/asana_rules/asana_service_account_created.yml
Labels: rules, packs

#664 new format for tags
  policies/aws_account_policies/aws_resource_minimum_tags.yml
  policies/aws_account_policies/aws_resource_required_tags.py
  policies/aws_account_policies/aws_resource_required_tags.yml
  policies/aws_ec2_policies/aws_ec2_ami_approved_host.yml
  policies/aws_ec2_policies/aws_ec2_ami_approved_instance_type.yml
  policies/aws_ec2_policies/aws_ec2_ami_approved_tenancy.yml
  policies/aws_ec2_policies/aws_ec2_instance_approved_ami.yml
  policies/aws_ec2_policies/aws_ec2_instance_approved_host.yml
  policies/aws_ec2_policies/aws_ec2_instance_approved_instance_type.yml
  policies/aws_ec2_policies/aws_ec2_instance_approved_tenancy.yml
  policies/aws_ec2_policies/aws_ec2_instance_approved_vpc.py
  policies/aws_ec2_policies/aws_ec2_instance_approved_vpc.yml
  policies/aws_ec2_policies/aws_ec2_instance_detailed_monitoring.yml
  policies/aws_ec2_policies/aws_ec2_instance_ebs_optimization.yml
Labels: bug, policies

#699 fix: sync policyuniverse version to backend
  Pipfile
  Pipfile.lock
Labels: dependencies
