Repository panther-labs/panther-analysis, pull requests merged in 2023-05, with the labels that each got.

#746 missing event in deep_get
  rules/aws_cloudtrail_rules/aws_modify_cloud_compute_infrastructure.py
Labels: bug

#749 Safely handle Zoom user group context
  rules/zoom_operation_rules/zoom_operation_passcode_disabled.py
  rules/zoom_operation_rules/zoom_operation_passcode_disabled.yml
Labels: bug

#754 feat: Tines.Audit detections and pack
  global_helpers/global_filter_tines.py
  global_helpers/global_filter_tines.yml
  global_helpers/global_helpers_test.py
  global_helpers/panther_tines_helpers.py
  global_helpers/panther_tines_helpers.yml
  packs/tines.yml
  rules/tines_rules/tines_sso_settings.py
  rules/tines_rules/tines_sso_settings.yml
Labels: rules, packs

#755 feat: Tines detections for API Tokens and CustomCA
  packs/tines.yml
  rules/tines_rules/tines_custom_ca.py
  rules/tines_rules/tines_custom_ca.yml
  rules/tines_rules/tines_tenant_authtoken.py
  rules/tines_rules/tines_tenant_authtoken.yml
Labels: rules

#760 chore: add a clickable link to snyk alert context to identify users
  global_helpers/global_helpers_test.py
  global_helpers/panther_snyk_helpers.py
Labels: bug

#764 feat: panther_oss_helpers.set_key_expiration should make an effort to turn epoch_seconds kwarg into an int
  Pipfile
  Pipfile.lock
  global_helpers/global_helpers_test.py
  global_helpers/panther_oss_helpers.py
Labels: bug

#763 fix: some cache ttls were getting stringified, which leads to dynamodb silently not expiring them
  rules/okta_rules/okta_geo_improbable_access.py
  rules/onelogin_rules/onelogin_high_risk_login.py
  rules/slack_rules/slack_application_dos.py
Labels: bug
