Repository panther-labs/panther-analysis, pull requests merged in 2025-07, with the labels that each got.

#1636 THREAT-509: GCP Compute Instance Sign-In
  indexes/alpha-index.md
  indexes/detection-coverage.json
  indexes/gcp.md
  packs/gcp_audit.yml
  rules/gcp_audit_rules/gcp_compute_ssh_connection.py
  rules/gcp_audit_rules/gcp_compute_ssh_connection.yml
Labels: rules

#1647 `Crowdstrike.Macos.Plutil.Usage` tuning
  rules/crowdstrike_rules/crowdstrike_macos_plutil_usage.py
Labels: tuning

#1651 update base streaming rule cursor rule
  .cursor/rules/caching.mdc
  .cursor/rules/panther-rules.mdc
  .cursor/rules/streaming-rules.mdc
Labels: documentation

#1552 Extract AWS account ID from unique ID
  global_helpers/default_test.py
  global_helpers/panther_aws_helpers.py
Labels: enhancement

#1653 fix(aws): fix alert title and include error message
  rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets.py
Labels: tuning

#1662 Fix latest changes link in Readme
  README.md
Labels: bug, documentation

#1658 ASK-2236 Increase in alerts for `GSuite suspicious login` rule
  indexes/alpha-index.md
  indexes/detection-coverage.json
  indexes/gworkspace.md
  indexes/saas.md
  packs/gsuite_reports.yml
  rules/gsuite_activityevent_rules/gsuite_is_suspicious_tag.py
  rules/gsuite_activityevent_rules/gsuite_is_suspicious_tag.yml
  rules/gsuite_activityevent_rules/gsuite_suspicious_logins.py
  rules/gsuite_activityevent_rules/gsuite_suspicious_logins.yml
Labels: tuning
