Repository panther-labs/panther-analysis, pull requests merged in 2025-05, with the labels that each got.

#1614 [THREAT-453] Remove set-output from Github Action
  .github/workflows/check-packs.yml
Labels: github_actions

#1616 ASK-1980 Snowflake queries syntax error
  queries/snowflake_queries/snowflake_brute_force_ip_query.yml
  queries/snowflake_queries/snowflake_brute_force_username_query.yml
Labels: bug

#1618 THREAT-500: Tuning Adjustments
  rules/cloudflare_rules/cloudflare_httpreq_bot_high_volume.py
  rules/snowflake_rules/snowflake_stream_login_without_mfa.yml
Labels: tuning

#1613 [THREAT-497] Add pre-commit hook
  .pre-commit-config.yaml
  Makefile
  Pipfile
  Pipfile.lock
  README.md
Labels: documentation

#1608 Okta VPN Login Title Enhancement
  rules/okta_rules/okta_anonymizing_vpn_login.py
Labels: tuning

#1583 Fiixing list conversion in AWS.CloudTrail.EventSelectorsDisabled
  rules/aws_cloudtrail_rules/aws_cloudtrail_event_selectors_disabled.py
Labels: bug

#1600 Fixup: AWS get_actor_user
  global_helpers/panther_aws_helpers.py
Labels: enhancement

#1601 A user-defined function to check the client's whitelisted IP address for impossible travel rule
  Pipfile
  Pipfile.lock
  global_helpers/panther_snowflake_helpers.py
  rules/standard_rules/impossible_travel_login.py
Labels: enhancement
