Repository panther-labs/panther-analysis, pull requests merged in 2025-04, with the labels that each got.

#1567 THREAT-479 AWS.Modify.Cloud.Compute.Infrastructure tuning
  rules/aws_cloudtrail_rules/aws_modify_cloud_compute_infrastructure.py
  rules/aws_cloudtrail_rules/aws_modify_cloud_compute_infrastructure.yml
Labels: tuning

#1559 ASK 1969 - Tuning Snowflake.BruteForceBy* Rules
  packs/snowflake.yml
  queries/snowflake_queries/snowflake_brute_force_ip.py
  queries/snowflake_queries/snowflake_brute_force_ip.yml
  queries/snowflake_queries/snowflake_brute_force_username.py
  queries/snowflake_queries/snowflake_brute_force_username.yml
  queries/snowflake_queries/snowflake_failed_logins_query.yml
Labels: tuning

#1556 ASK 1695 - GSuite Docs Download Row Too Long
  indexes/alpha-index.md
  indexes/detection-coverage.json
  indexes/gworkspace.md
  indexes/saas.md
  packs/gsuite_reports.yml
  queries/gsuite_queries/GSuite_Many_Docs_Downloaded_Query.yml
  queries/gsuite_queries/gsuite_drive_many_docs_downloaded.yml
  rules/gsuite_activityevent_rules/google_workspace_many_docs_downloaded.py
  rules/gsuite_activityevent_rules/google_workspace_many_docs_downloaded.yml
Labels: tuning

#1563 THREAT-482 Azure Risk passthrough tuning
  rules/azure_signin_rules/azure_risklevel_passthrough.yml
Labels: tuning

#1568 THREAT-481 GCP K8s tuning
  rules/gcp_audit_rules/gcp_logging_settings_modified.py
  rules/gcp_k8s_rules/gcp_k8s_pod_attached_to_node_host_network.py
Labels: tuning

#1582 [fix] ASK-1780 Snowflake. DataTransferHistory rule using non-existent field
  rules/snowflake_rules/snowflake_stream_external_shares.py
  rules/snowflake_rules/snowflake_stream_external_shares.yml
Labels: bug

#1571 update comp keys rule
  indexes/alpha-index.md
  indexes/aws.md
  indexes/detection-coverage.json
  rules/aws_cloudtrail_rules/aws_key_compromised.py
  rules/aws_cloudtrail_rules/aws_key_compromised.yml
Labels: tuning

#1584 Add dedup to GCP.Destructive.Queries
  rules/gcp_audit_rules/gcp_destructive_queries.py
Labels: tuning

#1540 THREAT 454: add rule: Orca.Passthrough
  indexes/alpha-index.md
  indexes/detection-coverage.json
  packs/orca.yml
  rules/orca_rules/orca_passthrough.py
  rules/orca_rules/orca_passthrough.yml
Labels: rules

#1586 Add mcp.json to gitignore
  .gitignore
Labels: enhancement

#1593 Beta rules
  correlation_rules/aws_create_admin_iam_user.yml
  queries/aws_queries/aws_ssm_multiple_sessions.yml
  queries/aws_queries/ec2_discovery_commands.yml
  rules/aws_cloudtrail_rules/aws_add_malicious_lambda_extension.yml
  rules/aws_cloudtrail_rules/aws_backdoor_lambda_function.yml
  rules/aws_cloudtrail_rules/aws_cloudtrail_attempt_to_leave_org.yml
  rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_identity_verifications.yml
  rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_send_quota.yml
  rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_ses_sending_enabled.yml
  rules/aws_cloudtrail_rules/aws_cloudtrail_ses_list_identities.yml
  rules/aws_cloudtrail_rules/aws_cloudtrail_short_lifecycle.yml
  rules/aws_cloudtrail_rules/aws_dns_logs_deleted.yml
  rules/aws_cloudtrail_rules/aws_ec2_launch_unusual_ec2_instances.yml
  rules/aws_cloudtrail_rules/aws_ec2_many_passwors_read_attempts.yml
  rules/aws_cloudtrail_rules/aws_ec2_multi_instance_connect.yml
  rules/aws_cloudtrail_rules/aws_overwrite_lambda_code.yml
  rules/aws_cloudtrail_rules/aws_s3_delete_object.yml
  rules/aws_cloudtrail_rules/aws_s3_delete_objects.yml
  rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets.yml
  rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets_batch.yml
  rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets_catchall.yml
  rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets_multiregion.yml
  rules/aws_cloudtrail_rules/aws_ssm_decrypt_ssm_params.yml
  rules/aws_cloudtrail_rules/aws_ssm_distributed_command.yml
  rules/aws_cloudtrail_rules/aws_vpc_flow_logs_deleted.yml
Labels: tuning

#1580 Unusual EC2 launch logic fixup
  rules/aws_cloudtrail_rules/aws_ec2_launch_unusual_ec2_instances.py
Labels: bug

#1597 GCP.Destructive.Queries: More tuning
  rules/gcp_audit_rules/gcp_destructive_queries.py
  rules/gcp_audit_rules/gcp_destructive_queries.yml
Labels: tuning

#1606 Google.Workspace.ManyDocsDownloaded: Convert to Signal
  rules/gsuite_activityevent_rules/google_workspace_many_docs_downloaded.py
  rules/gsuite_activityevent_rules/google_workspace_many_docs_downloaded.yml
Labels: tuning

#1602 THREAT-431 Update AWS rules to use new `get_actor_user` udm
  rules/aws_cloudtrail_rules/aws_console_login_without_mfa.py
  rules/aws_cloudtrail_rules/aws_console_login_without_mfa.yml
  rules/aws_cloudtrail_rules/aws_ec2_many_passwors_read_attempts.py
  rules/aws_cloudtrail_rules/aws_software_discovery.py
  rules/aws_cloudtrail_rules/aws_unauthorized_api_call.py
  rules/aws_cloudtrail_rules/aws_vpce_access_denied.py
  rules/aws_cloudtrail_rules/aws_vpce_external_principal.py
  rules/aws_cloudtrail_rules/aws_waf_disassociation.py
Labels: enhancement

#1607 THREAT-496 Automate Airflow update process
  .github/workflows/airflow-update.yml
Labels: github_actions

#1603 THREAT 498: Mark Policies as Configuration Required
  packs/aws.yml
  packs/aws_cis.yml
  policies/aws_account_policies/aws_password_policy_complexity_guidelines.py
  policies/aws_account_policies/aws_password_policy_complexity_guidelines.yml
  policies/aws_dynamodb_policies/aws_dynamodb_table_ttl_enabled.py
  policies/aws_dynamodb_policies/aws_dynamodb_table_ttl_enabled.yml
  policies/aws_ec2_policies/aws_ami_private.py
  policies/aws_ec2_policies/aws_ec2_cde_volume_encrypted.py
  policies/aws_guardduty_policies/aws_guardduty_enabled.py
  policies/aws_guardduty_policies/aws_guardduty_enabled.yml
  policies/aws_iam_policies/aws_iam_role_github_actions_trust.py
  policies/aws_iam_policies/aws_iam_role_github_actions_trust.yml
  policies/aws_load_balancer_policies/aws_elbv2_load_balancer_has_ssl_policy.py
  policies/aws_rds_policies/aws_rds_instance_backup_retention_acceptable.py
  policies/aws_redshift_policies/aws_redshift_cluster_snapshot_retention_acceptable.py
  policies/aws_s3_policies/aws_s3_bucket_object_lock_configured.py
  policies/aws_vpc_policies/aws_network_acl_restricts_inbound_traffic.py
  policies/aws_vpc_policies/aws_network_acl_restricts_insecure_protocols.py
  policies/aws_vpc_policies/aws_network_acl_restricts_outbound_traffic.py
  policies/aws_vpc_policies/aws_only_dmz_security_groups_publicly_accessible.py
  policies/aws_vpc_policies/aws_security_group_restricts_access_to_cde.py
  policies/aws_vpc_policies/aws_security_group_restricts_inbound_traffic.py
  policies/aws_vpc_policies/aws_security_group_restricts_inter_security_group_traffic.py
  policies/aws_vpc_policies/aws_security_group_restricts_outbound_traffic.py
  policies/aws_vpc_policies/aws_security_group_restricts_traffic_leaving_cde.py
  policies/aws_vpc_policies/aws_vpc_default_network_acl_restricts_all_traffic.py
  policies/aws_waf_policies/aws_waf_has_xss_predicate.py
Labels: tuning

#1610 Update aws_unauthorized_api_call.py by adding p_log_type
  rules/aws_cloudtrail_rules/aws_unauthorized_api_call.yml
Labels: bug
