Repository panther-labs/panther-analysis, pull requests merged in 2025-08, with the labels that each got.

#1678 Schema fix for managed LUTs
  .vscode/schemas/lookup_table.json
Labels: bug

#1664 Update MITRE mapping: Amazon.EKS.Audit.SystemNamespaceFromPublicIP
  rules/aws_eks_rules/system_namespace_public_ip.yml
Labels: documentation

#1666 Add support for GCP Service Manager to GCP.IAM.CorporateEmail
  packs/gcp_audit.yml
  rules/gcp_audit_rules/gcp_iam_corp_email.py
  rules/gcp_audit_rules/gcp_iam_corp_email.yml
Labels: tuning

#1687 Box remove api calls
  deprecated.txt
  global_helpers/panther_audit.py
  global_helpers/panther_audit.yml
  global_helpers/panther_box_helpers.py
  indexes/alpha-index.md
  indexes/detection-coverage.json
  indexes/saas.md
  rules/box_rules/box_item_shared_externally.py
  rules/box_rules/box_item_shared_externally.yml
Labels: dependencies

#1684 Add PantherEvent type hints
  global_helpers/panther_type_hints.py
  global_helpers/panther_type_hints.yml
Labels: enhancement, dependencies
